In [3]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv(r'C:\Users\HP\Desktop\Set C\Data\courses.csv')
df

  course_id   course  department
0        C1    Excel    Business
1        C2  PowerBI    Business
2        C3      SQL  Technology
3        C4   Python  Technology

In [8]:
df1 = pd.read_csv(r'C:\Users\HP\Desktop\Set C\Data\assessments.csv')
df1

    assessment_id month course_id    batch  score  attendance_pct
0               1   Jan        C1  Morning     72              90
1               2   Jan        C2  Evening     45              70
2               3   Jan        C3  Morning     65              85
3               4   Jan        C4  Weekend     38              60
4               5   Feb        C1  Evening     80              95
5               6   Feb        C2  Weekend     55              80
6               7   Feb        C3  Morning     48              75
7               8   Feb        C4  Evening     68              88
8               9   Mar        C1  Weekend     90              98
9              10   Mar        C2  Morning     60              82
10             11   Mar        C3  Evening     75              92
11             12   Mar        C4  Weekend     42              65
12             12   Mar        C4  Weekend     42              65